name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build collection
        run: |
          ansible-galaxy collection build

      - name: Publish collection
        run: |
          ansible-galaxy collection publish widespot-vars_config-*.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}
